#!/bin/bash
# Usage: sudo bash install_aocc

cd /tmp || exit 42

wget "https://www.dropbox.com/s/5xxfpr0tx8kn0o1/aocc-compiler-4.0.0_1_amd64.deb" -O aocc.deb

apt install /tmp/aocc.deb

SETENVSH="$(find /opt/AMD/ -name "*setenv*.sh" -type f -print | sort | tail -n 1)"

cp "$SETENVSH" /tmp/setenv.sh

printf "\n\n*** Remember to run the following before using AOCC flang:\n"
printf "\n    source %s\n\n" "$SETENVSH"
