#!/bin/bash
# Usage: bash install_sunf95

cd /tmp/ || exit 42

wget "https://www.dropbox.com/s/ayi572hcf5drdvk/OracleDevStd.zip" -O OracleDevStd.zip

unzip /tmp/OracleDevStd.zip

echo "PATH=$PATH:/tmp/OracleDevStd/bin" >> "$GITHUB_ENV"
echo "LD_LIBRARY_PATH=/tmp/OracleDevStd/lib/compilers/sys/amd64:/tmp/OracleDevStd/lib/compilers/sys/:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"
