#!/bin/bash
# Usage: sudo bash install_flang

apt install p7zip-full libncurses* # libncurses* needed for libtinfo.so

cd /tmp/ || exit 42

wget "https://www.dropbox.com/s/myhdi239myw1tsi/flang.7z"
7za x flang.7z

# Set environment variable for subsequent steps
echo "PATH=$PATH:/tmp/flang/bin" >> "$GITHUB_ENV"
echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp/flang/lib" >> "$GITHUB_ENV"
