#!/bin/bash
# Usage: sudo bash install_epstopdf

URL="https://tug.org/svn/texlive/trunk/Build/extra/epstopdf/epstopdf.pl?view=co"
apt install -y wget
wget "$URL" -O /usr/bin/epstopdf
chmod +x /usr/bin/epstopdf
