#!/bin/bash
# Usage: bash install_g95

cd /tmp/ || exit 42

git clone https://github.com/zaikunzhang/resources

cd resources/ || exit 42

unzip g95.zip

# Set environment variable for subsequent steps
echo "PATH=$PATH:/tmp/resources/g95/bin:/tmp/resources/g95/lib/gcc-lib/x86_64-unknown-linux-gnu/4.0.3" >> "$GITHUB_ENV"
