#!/bin/bash
# This script installs MatCUTEst using the compiled MatCUTEst in the current directory or $GITREPO.
# Usage: bash install_matcutest
# CUTEst version: 20230105

if [[ "$OSTYPE" != "linux-gnu"* ]]; then
    printf "\nThis package supports only GNU/Linux, not %s.\n\n" "$OSTYPE"
    exit 42
fi

if [[ "$1" = --full ]] ; then
    PKG="matcutest.full.7z"  # The full package containing all problems at https://bitbucket.org/optrove/sif
else
    PKG="matcutest.7z"  # A customized package containing the problems at https://github.com/zaikunzhang/my_cutest_sif
fi
PKG_NAME="${PKG//.*/}"  # Remove the suffix from $PKG

#GIT="gitee.com"
GIT="github.com"
GIT_USR="equipez"
REPONAME="$PKG_NAME"_compiled
GITREPO="https://$GIT/$GIT_USR/$REPONAME"  # Used only if $PKG does not exist in the current directory

INSTALL_DIR="$HOME/local"  # CUTEst will be installed $INSTALL_DIR/$PKG_NAME
TMPDIR="/tmp"

if command -v 7z &> /dev/null ; then
    DECOMP="$(command -v 7z) x"  # Command to decompress the package
else
    printf "\nError: 7z is needed to decompress the package, yet it is not installed.\n\n"
    exit 1
fi

mkdir -p "$INSTALL_DIR"
if [[ -d "$INSTALL_DIR"/"$PKG_NAME" ]] ;then
    # Exit if the package seems to have be installed.
    printf "\nThe package path\n\n%s\n\nalready exists. Remove it to (re-)install the package.\n\n" "$INSTALL_DIR"/"$PKG_NAME"
    exit 2
elif [[ -f "./$PKG" ]] ; then
    # If $PKG exists in the current directory, use it.
    cp "./$PKG" "$INSTALL_DIR"
else
    # If $PKG does not exist in the current directory, download it.
    cd "$TMPDIR" && rm -rf "$REPONAME" && git clone "$GITREPO"
    mv "$TMPDIR"/"$REPONAME"/$PKG "$INSTALL_DIR"
fi

cd "$INSTALL_DIR" && $DECOMP $PKG  || exit 3  # "$DECOMP $PKG" does not work
rm -f "$INSTALL_DIR"/"$PKG"

printf "\n\n*** Remember to invoke the M function \`locate_matcutest\` before using MatCUTEst."
printf "\n*** See locate_matcutest.m.\n\n"

exit 0
