#!/usr/bin/bash

if [[ $# -lt 1 ]]; then
    printf "\nPlease provide the version of gfortran to link.\n\n"
    exit 1
fi

REQUESTED_GFORTRAN_VERSION="$1"

GFORTRAN_PATH="/usr/bin/gfortran"

REQUESTED_GFORTRAN="gfortran-""$REQUESTED_GFORTRAN_VERSION"

apt install "$REQUESTED_GFORTRAN"

REQUESTED_GFORTRAN_PATH="$(realpath "$(command -v "$REQUESTED_GFORTRAN")")"

if [[ -f "$GFORTRAN_PATH" ]] ; then
    mv "$GFORTRAN_PATH" "$GFORTRAN_PATH".bak
fi

ln -s "$REQUESTED_GFORTRAN_PATH" "$GFORTRAN_PATH"

realpath "$(command -v gfortran)"

exit 0
