#!/bin/bash
# This script generates a "base" version of the code.

# The directory where this scrip resides
NEUPDFODIR="$(realpath "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )")"

# Prepare the base
BASEDIR="$NEUPDFODIR"/base
VERSION=$(date +%y%m%d)
BDIR="$BASEDIR"/"$VERSION"
mkdir -p "$BDIR"
cp -r "$NEUPDFODIR"/fsrc "$BDIR"
cp "$NEUPDFODIR"/setup.m "$BDIR"
cp -r "$NEUPDFODIR"/OPDFO "$BDIR"
cp -r "$NEUPDFODIR"/PDFO "$BDIR"
cp -r "$NEUPDFODIR"/matlab "$BDIR"
rm -r "$BDIR"/matlab/tests/testdata

# Update the OPDFO to the current version of PDFO
mv OPDFO OPDFO_"$VERSION"
mkdir OPDFO
cp -r "$NEUPDFODIR"/fsrc OPDFO

cp "$NEUPDFODIR"/setup.m OPDFO
sed -i "s/ALLn/ALL/g" OPDFO/setup.m

cp -r "$NEUPDFODIR"/matlab OPDFO
sed -i 's/solver(1:end-1)/solver/' OPDFO/matlab/setup_tools/compile.m

rm -r OPDFO/matlab/tests/testdata

MINTRFDIR=OPDFO/matlab/interfaces
rm -f "$MINTRFDIR"/private/*mexa64

for WORD in cobyla uobyqa newuoa bobyqa lincoa pdfo ; do
    WORDN="$WORD"n
    mv "$MINTRFDIR"/"$WORDN".m "$MINTRFDIR"/"$WORD".m
    find OPDFO -type f -exec sed -i -e "s/$WORDN/$WORD/g" {} \;
done

exit 0
