#!/bin/bash
#
# N.B.: Execute checktest by  "bash ./checktest" instead of just "./checktest", because
# "./checktest" may not be executable on all operating systems.

if [ ! $# -eq 2 ] ; then
	printf "Usage: checktest -w|--warning|-e|--error LOGFILE\n"
	exit 2
fi

LOGFILE="$2"

case "$1" in
	-w|--warning)
        WARNINGS="$(grep -i "warning" "$LOGFILE" | grep -vi "[0-9]\s*warning")"
        if [ -n "$WARNINGS" ]; then
            printf "\n\n-----------------------------------------------------------------------\n\n"
            printf "Warnings have been found in %s:\n\n" "$LOGFILE"
			cat "$LOGFILE"
            printf "\n\n-----------------------------------------------------------------------\n\n"
            printf "***********************************************************************\n\n"
            printf "Warnings logged in %s:\n\n" "$LOGFILE"
            printf "%s" "$WARNINGS"
            printf "\n\n***********************************************************************\n\n"
		fi
		exit 0
		;;
	-e|--error)
        ERRORS="$(grep -i "erro\|fail\|exception\|invalid\|overflow\|backtrace" "$LOGFILE" \
            | grep -vi "[0-9]\s*error" \
            | grep -vi "Warning:\ Floating\ overflow\ occurred" \
            | grep -vi "Warning:\ Floating\ invalid\ operation\ occurred" \
            | grep -vi "maxfun\|maxhist\|npt\|rhobeg\|rhoend\|ftarget")"
        if [ -n "$ERRORS" ]; then
            printf "\n\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n\n"
            printf "Errors have been found in %s:\n\n" "$LOGFILE"
			cat "$LOGFILE"
            printf "\n\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n\n"
            printf "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n\n"
            printf "Errors logged in %s:\n\n" "$LOGFILE"
            printf "%s" "$ERRORS"
            printf "\n\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n\n"
			exit 1
		else
			exit 0
		fi
		;;
	*)
		exit 3
		;;
esac
