#!/bin/bash
#
# N.B.: Execute checktest by  "bash ./checktest" instead of just "./checktest", because
# "./checktest" may not be executable on all operating systems.

if [ ! $# -eq 2 ] ; then
	printf "Usage: checktest -w|--warning|-e|--error LOGFILE\n"
	exit 2
fi

LOGFILE="$2"

case "$1" in
	-w|--warning)
        WARNINGS="$(grep -i "warning" "$LOGFILE" \
            | grep -vi "WARNING --  When --chk x is specified" \
            | grep -vi "[0-9]\s*warning" \
            | grep -vi "in __debug_mod_MOD_warning" \
            | grep -vi "MAXFILT is too small" \
            | grep -vi "Only the history of the last [0-9]* iteration(s) is recorede" \
            | grep -vi "invalid maxfun\|invalid maxhist\|invalid npt\|invalid rhobeg\|invalid rhoend\|invalid ftarget\|invalid ctol\|invalid maxfilt\|errstop")"
        if [ -n "$WARNINGS" ]; then
            printf "\n\n-----------------------------------------------------------------------\n"
            printf "| Warnings have been found in %s:\n\n" "$LOGFILE"
            sed "s/^/| /" "$LOGFILE"
            printf "\n|-----------------------------------------------------------------------\n\n"
            printf "***********************************************************************\n"
            printf "* Warnings logged in %s:\n\n" "$LOGFILE"
            printf "%s" "$(echo "$WARNINGS" | sed "s/^/* /")"
            printf "\n***********************************************************************\n\n"
		fi
		exit 0
		;;
	-e|--error)
        ERRORS="$(grep -i "err\|fail\|exception\|invalid\|bad\|overflow\|backtrace\|segmentation\|fault" "$LOGFILE" \
            | grep -vi "libbacktrac" \
            | grep -vi "[0-9]\s*error" \
            | grep -vi "Warning: [A-Z]*MS.*G: Failed to open file .*_output" \
            | grep -vi "Warning:\ Floating\ overflow\ occurred" \
            | grep -vi "Warning:\ Floating\ invalid\ operation\ occurred" \
            | grep -vi "flist:.*: Invalid format" \
            | grep -vi "BAD_TRSTEP" \
            | grep -vi "invalid maxfun\|invalid maxhist\|invalid npt\|invalid rhobeg\|invalid rhoend\|invalid ftarget\|invalid ctol\|invalid maxfilt\|errstop")"
        if [ -n "$ERRORS" ]; then
            printf "\n\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
            printf "+ Errors have been found in %s:\n\n" "$LOGFILE"
            sed "s/^/+ /" "$LOGFILE"
            printf "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n\n"
            printf "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"
            printf "X Errors logged in %s:\n\n" "$LOGFILE"
            printf "%s" "$(echo "$ERRORS" | sed "s/^/X /")"
           printf "\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\n"
			exit 1
		else
			exit 0
		fi
		;;
	*)
		exit 3
		;;
esac
