#!/bin/bash
# This script prepares the Fortran source code for lf95, which does not support the following:
# ```
# public ::
# use, intrinsic ::
# use, non_intrinsic ::
# abstract interface
# [] as array constructor
# ```
# Usage: lfsrc DIR

# The full path of the directory to proceed
DIR="$(realpath "$1")"

# Temporary file
TMP="/tmp/tmp.$(date +%s)"

# The files that contain abstract interfaces.
UNIVARF90="univar.f90"
UNIVAR="$DIR/common/$UNIVARF90"
INTRF_UNIVAR="$DIR/common/intrf_$UNIVARF90"
PINTRFF90="pintrf.f90"
PINTRF="$DIR/common/$PINTRFF90"

# Exit if DIR is not a testing directory.
if ! basename "$DIR" | grep -q "\.test\|test\.\|\.tst\|tst\." || ! [[ -d "$DIR" ]] ; then
    printf "\n%s is not a testing directory.\n\nExit.\n\n" "$DIR"
    exit 1
fi

# For UNIVAR, first print the interface into a file
sed -n '/abstract interface/,/end interface/p' "$UNIVAR" \
    | sed 's/abstract interface/interface/' \
    | sed 's/FUNC_WITH_ARGS/fun/g' \
    > "$INTRF_UNIVAR"
# Remove the interface from UNIVAR
sed -n '/abstract interface/,/end interface/!p' "$UNIVAR" > "$TMP" && cat "$TMP" > "$UNIVAR"
# Replace "^procedure(FUNC_WITH_ARGS) :: fun$" with "include \"$INTRF_UNIVAR\""
sed -i "s|^procedure(FUNC_WITH_ARGS) :: fun$|include \"$INTRF_UNIVAR\"|" "$UNIVAR"

# For PINTRF, remove the lines before "public :: " (included) and the line "end module"; then
# replace "abstract interface" with "interface", "OBJCON" with "calcfc", and "OBJ" with "calfun".
sed -i '0,/^\s*public ::/d ; /^\s*end module/d ; s/abstract interface/interface/ ; s/OBJCON/calcfc/g ; s/OBJ/calfun/g' "$PINTRF"

# For any Fortran file under DIR, remove ", [non_]intrinsic ::"`, replace "[]" with "\(\)", remove
# "use pintrf_mod", replace "procedure(OBJ) :: calfun" and "procedure(OBJCON)" with "include $PINTRF".
find "$DIR" -type f \( -name "*.f90" -o -name "*.F90" \) -print0 \
    | xargs -0 sed -i "s/, .*intrinsic ::// ; s/\[/\(\//g ; s/\]/\/\)/g ; /^\s*use pintrf_mod/d ; \
    s|^procedure(OBJ) :: calfun$|include \"$PINTRF\"| ; s|^procedure(OBJCON) :: calcfc$|include \"$PINTRF\"|"

find "$DIR" -type f  -name "ffiles.txt" -print0 | xargs -0 sed -i "/^$PINTRFF90$/d"



exit 0
