#!/bin/bash
# This script pre-processes the Fortran source code for g95 and Absoft af95.
# 1. They do not recognize the `back` keyword in `min/maxloc`, which is available since F2008.
# 2. They do not support allocatable characters (variable length strings), which is F2003.
# 3. af95 does not support `error stop`, which is F2003.

DIR="$(realpath "$1")"
GETACTF90="getact.f90"
GETACT="$DIR/lincoa/$GETACTF90"
STRINGF90="string.f90"
STRING="$DIR/common/$STRINGF90"
PREPROCF90="preproc.f90"
PREPROC="$DIR/common/$PREPROCF90"
LINALGF90="linalg.f90"
LINALG="$DIR/common/$LINALGF90"
OUTPUTF90="output.f90"
OUTPUT="$DIR/common/$OUTPUTF90"
DEBUGF90="debug.F90"
DEBUG="$DIR/common/$DEBUGF90"
NOISEF90="noise.f90"
NOISE="$DIR/testsuite/$NOISEF90"
FMXAPIF90="fmxapi.F90"
FMXAPI="$DIR/$FMXAPIF90"

if ! basename "$DIR" | grep -q ".test\|test." || ! [[ -d "$DIR" ]] ; then
    printf "\n%s is not a testing directory.\n\nExit.\n\n" "$DIR"
    exit 1
fi

if [[ -f "$GETACT" ]] ; then
    sed -i "s/,\s*back\s*=\s*\.true\.//" "$GETACT"
fi

for FILE in "$STRING" "$PREPROC" "$LINALG" "$OUTPUT" "$DEBUG" "$NOISE" "$FMXAPI" ; do
    if [[ -f "$FILE" ]] ; then
        sed -i "s/character(len=:), allocatable/character(len=1024)/" "$FILE"
    fi
done

if [[ -f "$DEBUG" ]] ; then
    sed -i "s|^error stop|stop|" "$DEBUG"
fi

exit 0
