#!/bin/bash
# This script generates a "base" version of the code.

# The directory where this scrip resides
THISDIR="$(realpath "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )")"
PRIMADIR="$(dirname "$THISDIR")"

# Remove the unwanted files.
find "$PRIMADIR" -name core -type f -delete
find "$PRIMADIR" -name core.* -type f -delete
find "$PRIMADIR" -name *.mexa64 -type f -delete
find "$PRIMADIR" -name *.mod -type f -delete
find "$PRIMADIR"  -name ".interform" -type d -exec rm -rf {} \;
find "$PRIMADIR"  -name "flog" -type d -exec  rm -r {} \;
find "$PRIMADIR"  -name "mlog" -type d -exec  rm -r {} \;
ORIGINAL="$PRIMADIR"/fortran/original
for SOLVER in cobyla uobyqa newuoa bobyqa lincoa ; do
    cd "$ORIGINAL"/"$SOLVER" && make clean
done

# Directory of the last version, which will be used as the reference version in the development of
# the new version.
LAST="$PRIMADIR"/last

# Copy the current version (together with the corresponding last version) into $BASEDIR, so that it
# becomes a new base.
BASEDIR="$PRIMADIR"/base
VERSION=$(date +%y%m%d)
BVDIR="$BASEDIR"/"$VERSION"
mkdir -p "$BVDIR"
cp -r "$LAST" "$BVDIR"
cp -r "$PRIMADIR"/fortran "$BVDIR"
cp "$PRIMADIR"/setup.m "$BVDIR"
mkdir "$BVDIR"/matlab
cp -r "$PRIMADIR"/matlab "$BVDIR"
rm -r "$BVDIR"/matlab/tests/testdata

# Copy the current version to "$LAST".
mv "$LAST" "$LAST"_"$VERSION"
mkdir "$LAST"
cp -r "$PRIMADIR"/fortran "$LAST"
cp "$PRIMADIR"/setup.m "$LAST"
mkdir "$LAST"/matlab
for DIR in setup_tools mex_gateways interfaces ; do
    cp -r "$PRIMADIR"/matlab/"$DIR" "$LAST"/matlab
done

# Modify the code in "$LAST"/matlab so that it becomes the "new last version".
MSETUPTOOLS="$LAST"/matlab/setup_tools
MINTERFACES="$LAST"/matlab/interfaces
rm -f "$MINTERFACES"/private/*mexa64
for WORD in cobyla uobyqa newuoa bobyqa lincoa prima ; do
    WORDL="$WORD"_last
    mv "$MINTERFACES"/"$WORD".m "$MINTERFACES"/"$WORDL".m
    for DIR in "$MSETUPTOOLS" "$MINTERFACES" ; do
        find "$DIR" -type f -exec sed -i -e "s|$WORD|$WORDL|g" {} \;
    done
done
for WORD in preprima postprima ; do
    WORDL="$WORD"_last
    mv "$MINTERFACES"/private/"$WORD".m "$MINTERFACES"/private/"$WORDL".m
done

# Modify the names of the MATLAB version of the solvers in "$LAST/matlab". This must be done because
# there invocations have been changed in the last step.
#for SOLVER in cobyla uobyqa newuoa bobyqa lincoa ; do
for SOLVER in newuoa ; do  # As of 2023010, only the MATLAB version of NEWUOA is implemented.
    MATPKG="$MINTERFACES"/+"$SOLVER"_mat
    MATPKGL="$MINTERFACES"/+"$SOLVER"_last_mat
    MATSOLVER="$SOLVER"_mat.m
    MATSOLVERL="$SOLVER"_last_mat.m
    mv "$MATPKG" "$MATPKGL"
    mv "$MATPKGL"/"$MATSOLVER" "$MATPKGL"/"$MATSOLVERL"
done

# Modify compile.m for the new last version.
COMPILEM="$LAST"/matlab/setup_tools/compile.m
OLDSTR="solver = solvers{isol}"
NEWSTR="solver = regexprep(solvers{isol}, '_last', '')"
sed -i "s|$OLDSTR|$NEWSTR|" "$COMPILEM"
OLDSTR="get_mexname(solver"
NEWSTR="get_mexname(solvers{isol}"
sed -i "s|$OLDSTR|$NEWSTR|" "$COMPILEM"

exit 0
