#!/bin/bash

# Commit submodules
ROOTDIR=$(git rev-parse --show-toplevel)
for SUBMODULE in $(git submodule status | awk '{print $2}'); do
    SMDIR="$ROOTDIR/$SUBMODULE"
    echo "Committing $SUBMODULE ..."
    cd "$SMDIR" || (printf "Error: submodule %s not found\n" "$SMDIR" && exit 1)
    git add -A
    git commit -m "Update $SUBMODULE"
done
cd "$ROOTDIR" || exit 2

exit 0
