#!/bin/bash

sed -i 's/DABS/ABS/g' *.f*
sed -i 's/DSQRT/SQRT/g' *.f*
sed -i 's/DSIN/SIN/g' *.f*
sed -i 's/DCOS/COS/g' *.f*
sed -i 's/DATAN/ATAN/g' *.f*
sed -i 's/DMIN1/MIN/g' *.f*
sed -i 's/DMAX1/MAX/g' *.f*
sed -i 's/DSIGN/SIGN/g' *.f*
