#!/bin/bash

# The directory where this script resides. It is the solver's directory.
SOLVER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# The log directory in the solver's directory.
SOLVER_LOG_DIR="$SOLVER_DIR"/log

# The solver's name.
SOLVER=$(basename "$SOLVER_DIR")

# The testing directory.
TEST_DIR="$SOLVER_DIR"/../tests
# The log directory in the testing directory.
TEST_LOG_DIR="$TEST_DIR"/test."$SOLVER"/log

# Remove the old logs.
mkdir -p "$SOLVER_LOG_DIR"
rm -f "$SOLVER_LOG_DIR"/*test*_c.log

# Conduct the test.
cd "$TEST_DIR" || exit 1

make cleanall."$SOLVER" > /dev/null

if lf95 --version  &> /dev/null ; then
    #COMPILER_LIST="g n 9 a s i v f d x l"
    COMPILER_LIST="g n 9 s i v f d x l"
else
    #COMPILER_LIST="g n 9 a s i v f d x"
    COMPILER_LIST="g n 9 s i v f d x"
fi

for COMPILER in $COMPILER_LIST; do
    if [[ $COMPILER == 'f' || $COMPILER == 'v' || $COMPILER == 'x' ]] ; then
        TESTS="i4_r8_d1 i4_r8_d0 i2_r4_d1 i8_r4_d1"
    else
        TESTS="i4_r8_d1 i4_r8_d0 i2_r16_d1 i8_r4_d1"
    fi
    for TEST in $TESTS ; do
        INFO="$(make "$COMPILER"test_"$TEST"_tst_c."$SOLVER" \
            | grep -i "starts\|warning\|error\|info\|fail\|abort\|questionable" \
            | grep -vi "[0-9]\s*warning\|[0-9]\s*error\|[0-9]\s*info\|info.f90\|information\|--warning\|--error" \
            | grep -v "interpolation error" \
            | grep -v "WARNING --  When --chk x is specified" \
            | grep -v "warning #10182: disabling optimization" \
            | grep -v "^- \|^| \|^\* \|^+ \|^X \|\# " \
            )"
        if [[ "$COMPILER" == "9" ]] ; then
            INFO="$(echo "$INFO" \
                | grep -v "Warning (165): Implicit interface 'calcfc' called at (1)" \
                | grep -v "Warning (165): Implicit interface 'calfun' called at (1)" \
                | grep -v "Warning (102): MODULE PROCEDURE 'calfun' USEd at (1) is not referenced" \
                | grep -v "Warning (102): MODULE PROCEDURE 'inv' USEd at (1) is not referenced" \
                )"
        elif [[ "$COMPILER" == "n" ]] ; then
            INFO="$(echo "$INFO" | grep -vi "Expression in IF construct is constant")"
        fi
        echo "$INFO" | grep -i --color "starts\|warning\|error\|info\|fail\||abort\|questionable"
        if echo "$INFO" | grep -iq "error\|fail\|abort" ; then
            if [[ -f "$TEST_LOG_DIR"/"$COMPILER"test_"$TEST"_tst_c.log ]] ; then
                LOGFILE="$COMPILER"test_"$TEST"_tst_c.log
            else
                LOGFILE="$COMPILER"test_c.log
            fi
            mv "$TEST_LOG_DIR"/"$LOGFILE" "$SOLVER_LOG_DIR"
            cat "$SOLVER_LOG_DIR"/"$LOGFILE"
            exit 2
        fi
    done
    mv "$TEST_LOG_DIR"/"$COMPILER"test*_c.log "$SOLVER_LOG_DIR"
done

make clean."$SOLVER"

# Check the logfiles
LOGFILES=("$SOLVER_LOG_DIR"/*test*_c.log)
for LOGFILE in "${LOGFILES[@]::${#LOGFILES[@]}-1}" ; do
    printf "\nChecking %s ...\n" "$LOGFILE"
    INFO="$(bash "$TEST_DIR"/checktest --warning "$LOGFILE")"
    printf "%s" "$INFO"
    printf "\nDone!\n"
    if [[ -n "$INFO" ]] ; then
        read -n1 -s -r -p $'Continue? [Y/n] ' KEY
        printf "\n"
        if ! [[ "$KEY" == 'Y' || "$KEY" == 'y' || "$KEY" == "" ]]; then
            exit 0
        fi
    fi
done
# No pause needed for the last logfile.
LOGFILE="${LOGFILES[-1]}"  # The last logfile; it needs Bash 4.x.
printf "\nChecking %s ...\n" "$LOGFILE"
bash "$TEST_DIR"/checktest --warning "$LOGFILE"
printf "%s" "$INFO"
printf "\nDone!\n\n"
