#!/bin/bash

if [ ! $# -eq 2 ] ; then
	printf "Usage: checktest -w|--warning|-e|--error LOGFILE\n"
	exit 2
fi

LOGFILE="$2"

case "$1" in
	-w|--warning)
		if grep -iq "warning" "$LOGFILE" ; then
			cat "$LOGFILE"
			grep -i "warning" "$LOGFILE"
		fi
		exit 0
		;;
	-e|--error)
		if grep -iq "error\|fail" "$LOGFILE" ; then
			cat "$LOGFILE"
			grep -i "error\|fail" "$LOGFILE"
			exit 1
		else
			exit 0
		fi
		;;
	*)
		exit 3
		;;
esac
