#!/bin/bash

SFILES=" $(cat ffiles.txt)"

COMMON=../../common
CFILES="$COMMON/consts.F90 \
    $COMMON/debug.F90 \
    $COMMON/infnan.F90 \
    $COMMON/memory.F90 \
    $COMMON/string.f90 \
    $COMMON/linalg.F90 \
    $COMMON/pintrf.f90 \
    $COMMON/evaluate.f90 \
    $COMMON/history.f90 \
    $COMMON/preproc.f90"
FFILES="$CFILES $SFILES"

rm -f *.dbg *.mod *.o *__genmod.f90
gfortran -c -g -Wall -Wextra -pedantic -Wampersand -Wconversion  -Wuninitialized -Wmaybe-uninitialized \
	-Wsurprising -Waliasing -Wintrinsics-std -Wunderflow \
	-Wuse-without-only -Wunused-parameter \
    -Wno-compare-reals \
	-fPIC -fimplicit-none -fbacktrace -fcheck=all \
	-finit-real=nan -finit-integer=-9999999 $FFILES

rm -f *.dbg *.mod *.o *__genmod.f90
nagfor -colour=error:red,warn:magenta,info:cyan -info -gline -u -C -C=alias -C=dangling -C=intovf -C=undefined -kind=unique -Warn=constant_coindexing -Warn=subnormal -c -g $FFILES

rm -f *.dbg *.mod *.o *__genmod.f90
ifort -warn all -debug extended -traceback -debug-parameters all -fp-stack-check -c -g $FFILES

rm -f *.dbg *.mod *.o *__genmod.f90
g95 -Wall -Wextra -Werror=100,113,115,137,146,147,159 -Wline-truncation -Wprecision-loss -Wunused-module-vars -Wunused-vars -Wunset-vars -fimplicit-none -fbounds-check -ftrace=full -freal=nan -fmodule-private -c -g $FFILES

rm -f *.dbg *.mod *.o *__genmod.f90
sunf95 -w3 -ansi -xcheck=%all -C -c -g $FFILES

rm -f *.dbg *.mod *.o *__genmod.f90
VFORT=$(find -L /opt/nvidia -type f -executable -name nvfortran -print 2> /dev/null | sort | tail -n 1)
$VFORT -Kieee -Ktrap=divz,ovf,inv,unf,denorm -c -g $FFILES

rm -f *.dbg *.mod *.o *__genmod.f90
AFLANG=$(find -L /opt/AMD -type f -executable -name flang -print 2> /dev/null | sort | tail -n 1)
$AFLANG -Weverything -Wall -Wextra -Minform=warn -Mstandard -Mbounds -Kieee -Mchkptr -c -g $FFILES

rm -f *.dbg *.mod *.o *__genmod.f90
ifx -warn all -debug extended -traceback -debug-parameters all -fp-stack-check -c -g $FFILES

rm -f *.dbg *.mod *.o *__genmod.f90
af95 -c -g -no-pie -m1 -en -et -Rb -Rc -Rs -Rp $FFILES

rm -f *.dbg *.mod *.o *__genmod.f90 *.cmdx *.cmod *.ilm *.stb
