#!/bin/bash

# use wget to fetch the Intel repository public key
cd /tmp
wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB

# add to your apt sources keyring so that archives signed with this key will be trusted.
sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB

# remove the public key
rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB

echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
sudo apt install intel-basekit intel-hpckit

if [[ -f /opt/intel/oneapi/setvars.sh ]] ; then
    source /opt/intel/oneapi/setvars.sh > /dev/null ; env | grep intel | sed "s/:\/User.*$//" \
        | sed 's/^/export /' > "/tmp/setenv.sh"
    source "/tmp/setenv.sh"
fi

IFORT="$(find /opt/*ntel* -type f -executable -name ifort -print -quit)"
IFX="$(find /opt/*ntel* -type f -executable -name ifx -print -quit)"
sudo ln -s "$IFORT" /usr/bin
sudo ln -s "$IFX" /usr/bin
