#!/bin/bash

wget https://developer.download.nvidia.com/hpc-sdk/21.7/nvhpc-21-7_21.7_amd64.deb \
  https://developer.download.nvidia.com/hpc-sdk/21.7/nvhpc-2021_21.7_amd64.deb

sudo apt install ./nvhpc-21-7_21.7_amd64.deb ./nvhpc-2021_21.7_amd64.deb

NVFORTRAN="$(find /opt/*nvidia* -type f -executable -name nvfortran -print -quit)"

sudo ln -s "$NVFORTRAN" /usr/bin
