#!/bin/bash

sed -i '/- name: Link gfortran for MATLAB on Linux/,/run: bash .github\/scripts\/link_gfortran \${{\ env.GFORTRAN_VERSION\ }}$/c\
      - name: Set up gfortran on Linux\
        if: startsWith(matrix.os, '\''ubuntu'\'')\
        uses: fortran-lang/setup-fortran@main\
        with:\
          compiler: gcc\
          version: \${{ env.GFORTRAN_VERSION }}\
      - name: Check gfortran version on Linux\
        if: startsWith(matrix.os, '\''ubuntu'\'')\
        run: which gfortran && gfortran --version' \
        $1
