#!/usr/bin/env bash
# This script pre-processes the Fortran source code for g95
# It does not support REAL32, REAL64, REAL128 in ISO_FORTRAN_ENV.
# It does not recognize the `back` keyword in `min/maxloc`, which is available since F2008.
# It does not support allocatable characters (variable length strings), which is F2003.
# It does not support `error stop code`, which is F2003.

DIR="$(realpath "$1")"
CONSTSF90="consts.F90"
CONSTS="$DIR/common/$CONSTSF90"
MEMORYF90="memory.F90"
MEMORY="$DIR/common/$MEMORYF90"
STRINGF90="string.f90"
STRING="$DIR/common/$STRINGF90"
CMN_FPRINTF90="fprint.f90"
CMN_FPRINT="$DIR/common/$CMN_FPRINTF90"
MEX_FPRINTF90="fprint.F90"
MEX_FPRINT="$DIR/common/$MEX_FPRINTF90"
UOBYQB="$DIR/uobyqa/uobyqb.f90"
NEWUOB="$DIR/newuoa/newuob.f90"
BOBYQB="$DIR/bobyqa/bobyqb.f90"
LINCOB="$DIR/lincoa/lincob.f90"
COBYLB="$DIR/cobyla/cobylb.f90"
GETACTF90="getact.f90"
GETACT="$DIR/lincoa/$GETACTF90"
PREPROCF90="preproc.f90"
PREPROC="$DIR/common/$PREPROCF90"
LINALGF90="linalg.f90"
LINALG="$DIR/common/$LINALGF90"
CMN_FPRINTF90="fprint.f90"
CMN_FPRINT="$DIR/common/$CMN_FPRINTF90"
MEX_FPRINTF90="fprint.F90"
MEX_FPRINT="$DIR/common/$MEX_FPRINTF90"
DEBUGF90="debug.F90"
DEBUG="$DIR/common/$DEBUGF90"
NOISEF90="noise.f90"
NOISE="$DIR/testsuite/$NOISEF90"
FMXAPIF90="fmxapi.F90"
FMXAPI="$DIR/$FMXAPIF90"
MESSAGEF90="message.f90"
MESSAGE="$DIR/common/$MESSAGEF90"


if ! basename "$DIR" | grep -q ".test\|test." || ! [[ -d "$DIR" ]] ; then
    printf "\n%s is not a testing directory.\n\nExit.\n\n" "$DIR"
    exit 1
fi

if [[ -f "$CONSTS" ]] ; then
    sed -i "/end module consts_mod/d" "$CONSTS"

    STR="use, intrinsic :: iso_fortran_env, only : INT16, INT32, INT64, SP => REAL32, DP => REAL64"
    sed -i "/$STR/d" "$CONSTS"
    STR="HP => REAL16"
    sed -i "/$STR/d" "$CONSTS"
    STR="QP => REAL128"
    sed -i "/$STR/d" "$CONSTS"
    OLD_STR="! Define the real kind to be used in the Fortran code."
    NEW_STR="$OLD_STR\ninteger, parameter :: SP = kind(0.0), DP = kind(0.0D0)\n#if PRIMA_QP_AVAILABLE\ninteger, parameter :: QP = selected_real_kind(p=30)\n#endif"
    sed -i "s/$OLD_STR/$NEW_STR/" "$CONSTS"
    OLD_STR="integer, parameter :: IK = INT16"
    NEW_STR="integer, parameter :: IK = selected_int_kind(4)"
    sed -i "s/$OLD_STR/$NEW_STR/" "$CONSTS"
    echo "integer, parameter :: INT16 = selected_int_kind(4)" >> "$CONSTS"
    OLD_STR="integer, parameter :: IK = INT32"
    NEW_STR="integer, parameter :: IK = selected_int_kind(7)"
    sed -i "s/$OLD_STR/$NEW_STR/" "$CONSTS"
    echo "integer, parameter :: INT32 = selected_int_kind(7)" >> "$CONSTS"
    OLD_STR="integer, parameter :: IK = INT64"
    NEW_STR="integer, parameter :: IK = selected_int_kind(14)"
    sed -i "s/$OLD_STR/$NEW_STR/" "$CONSTS"
    echo "integer, parameter :: INT64 = selected_int_kind(14)" >> "$CONSTS"

    echo "end module consts_mod" >> "$CONSTS"
fi

if [[ -f "$MEMORY" ]] ; then
    OLD_STR="y = int(storage_size(x) \/ 8, kind(y))"
    NEW_STR="y = int(8, kind(y))"
    sed -i "s/$OLD_STR/$NEW_STR/" "$MEMORY"
fi

if [[ -f "$STRING" ]] ; then
    sed -i "/ndgt_loc = min(ndgt_loc, floor(real(MAX_NUM_STR_LEN - 5) \/ 2.0))/d" "$STRING"
    sed -i "/nexp_loc = min(nexp_loc, floor(real(MAX_NUM_STR_LEN - 5) \/ 2.0))/d" "$STRING"
fi

for FILE in "$CMN_FPRINT" "$MEX_FPRINT" ; do
    if [[ -f "$FILE" ]] ; then
        sed -i "s|funit_loc = -1|funit_loc = 42|g" "$FILE"
        sed -i "s|newunit|unit|g" "$FILE"
    fi
done

# g95 does not support internal subroutines as arguments.
if [[ -f "$COBYLB" ]] ; then
    sed -ni '1,/\s*!\s*Calculation ends\s*!/p;/end subroutine cobylb/,$p' "$COBYLB"
    sed -i "s|calcfc_internal|calcfc|" "$COBYLB"
fi

for FILE in "$NEWUOB" "$UOBYQB" "$BOBYQB" ; do
    if [[ -f "$FILE" ]] ; then
        sed -i "s|terminate=terminate)|0.0_RP, [0.0_RP], terminate)|g" "$FILE"
    fi
done
if [[ -f "$LINCOB" ]]; then
   sed -i "s|terminate=terminate)|[0.0_RP], terminate)|g" "$LINCOB"
fi


if [[ -f "$GETACT" ]] ; then
    sed -i "s/,\s*back\s*=\s*\.true\.//" "$GETACT"
fi

for FILE in "$PREPROC" "$LINALG" "$CMN_FPRINT" "$MEX_FPRINT" "$DEBUG" "$NOISE" "$FMXAPI" ; do
    if [[ -f "$FILE" ]] ; then
        sed -i "s/character(len=:), allocatable/character(len=1024)/" "$FILE"
        sed -i "/character(len=\*), parameter :: newline/d" "$FILE"
        sed -i "s|newline|achar(10)|g" "$FILE"
    fi
done

if [[ -f "$STRING" ]] ; then
    sed -i "s/character(len=:), allocatable/character(len=1024)/" "$STRING"
    sed -i "/LEN(S) <= MAX_NUM_STR_LEN/d" "$STRING"
    sed -i "s/write (str, sformat) x/write(*,*) sformat; write (str, *) x/" "$STRING"
    sed -i "/character(len=\*), parameter :: newline/d" "$STRING"
    sed -i "s|newline|achar(10)|g" "$STRING"
fi

if [[ -f "$MEMORY" ]] ; then
    sed -i "s/character(len=:), allocatable/character(len=1024)/" "$MEMORY"
    sed -i "/allocate (character/d" "$MEMORY"
    sed -i "/call validate(allocated(x), 'X is allocated', srname)/d" "$MEMORY"
    sed -i "s/integer :: alloc_status/integer :: alloc_status = 0/" "$MEMORY"
fi

# message.f90 does not work due to the changes to string.f90, especially to real2str_vector.
(cd "$DIR" && grep -R 'call .*msg' | sed 's|:.*$||' | grep -v 'debug.F90\|fmxapi.F90' | xargs sed -i "s|call .*msg.*$|write(*,*) solver|" && cd - || exit 1) > /dev/null
(cd "$DIR" && grep -R 'use.*message_mod' | sed 's|:.*$||' | xargs sed -i "/use.*message_mod/d" && cd - || exit 1) > /dev/null
printf "module message_mod \n end module message_mod" > "$MESSAGE"

if [[ -f "$DEBUG" ]] ; then
    sed -i "s|^\s*error stop.*$|stop|" "$DEBUG"
fi

for SOL in cobyla uobyqa newuoa bobyqa lincoa ; do
    FILE="$DIR/test_$SOL.f90"
    if [[ -f $FILE ]] ; then
        sed -i "s|character(len=:), allocatable|character(len=1024)|g" "$FILE"
        sed -i "/safealloc(testdim.*$/d" "$FILE"
    fi
done

if [[ -d "$DIR"/lincoa ]] ; then
    for FILE in "$DIR"/lincoa/* ; do
        if [[ -f "$FILE" ]] ; then
            sed -i "s|count(xl > -REALMAX)|size(xl)|" "$FILE"
            sed -i "s|count(xu < REALMAX)|size(xu)|" "$FILE"
        fi
    done
    sed -i -e '/amat = reshape(shape=shape(amat)/,+3d' "$DIR"/lincoa/lincoa.f90
    sed -i '/idmat/d' "$DIR"/lincoa/lincoa.f90
fi

exit 0
