#!/usr/bin/env bash
# This script pre-processes the Fortran source code for Arm Flang.

DIR="$(realpath "$1")"
LINALG="$DIR/common/linalg.f90"
#GET_INTRISIC_LINALG="$DIR/common/get_intrinsic_linalg"
#INTRINSIC_LINALG="$DIR/common/intrinsic_linalg.f90"
LINCOB="$DIR/lincoa/lincob.f90"
INF="$DIR/common/inf.F90"

if [[ "$(uname)" = "Darwin" ]] ; then
    SEDI="sed -i ''"
else
    SEDI="sed -i"
fi

if ! basename "$DIR" | grep -q ".test\|test." || ! [[ -d "$DIR" ]] ; then
    printf "\n%s is not a testing directory.\n\nExit.\n\n" "$DIR"
    exit 1
fi

if [[ -f "$LINALG" ]] ; then
    # See https://github.com/llvm/llvm-project/issues/89528
    STR="Y is NaN if and only if X contains NaN"
    $SEDI "/$STR/d" "$LINALG"

    # # With flang-new 20.1.8, matprod in linalg.f90 often fails to compute matrix multiplications
    # # correctly, generating garbage values (NaN or numbers that are nearly zero). No idea why.
    # # The following is a workaround the replaces matprod with the intrinsic matmul.
    # # Remove this and test again when flang is updated.
    # Update 20250906: With flang-new 21.1.0, matprod seems to work fine now.
    # if [[ -f "$GET_INTRISIC_LINALG" ]] ; then
    #     bash "$GET_INTRISIC_LINALG"
    #     mv "$INTRINSIC_LINALG" "$LINALG"
    # fi
fi

if [[ -f "$LINCOB" ]] ; then
    # A bogus segfault is triggered in line 222 of lincob.f90 when testing ABS(IPRINT) <= 3.
    STR="call assert(abs(iprint) <= 3"
    $SEDI "/$STR/d" "$LINCOB"
    # A bogus segfault is triggered in line 233 of lincob.f90 when testing ALL(IS_FINITE(X)).
    STR="call assert(all(is_finite(x))"
    $SEDI "/$STR/d" "$LINCOB"
fi

# A bogus segfault is triggered in line 233 of lincob.f90 when testing ALL(IS_FINITE(X)).
# if [[ -f "$INF" ]] ; then
#     OLDSTR="y = (x <= huge_value(x) \.and\. x >= -huge_value(x))"
#     NEWSTR="y = .true. ; "
#     sed -i "s|$OLDSTR|$NEWSTR|g" "$INF"
#     cat "$INF"
# fi

exit 0
