#!/usr/bin/env bash
# This script pre-processes the Fortran source code for nvfortran.

DIR="$(realpath "$1")"
POWALG="$DIR/common/powalg.f90"

if ! basename "$DIR" | grep -q ".test\|test." || ! [[ -d "$DIR" ]] ; then
    printf "\n%s is not a testing directory.\n\nExit.\n\n" "$DIR"
    exit 1
fi

if [[ -f "$POWALG" ]] ; then
    # nvfortran 25.7.0 raises a false positive error of out-bound index for Anew(:, n+1:n) in
    # powalg.f90 when the solver is invoked with `-Mbounds -Ox` or `-C -Ox`, where x >= 2.
    # For example, the following command fails with the error:
    #
    # $export TESTDIM=small && export TESTSEED=2533 && export FFLAGS=-fast && make clean && make vtest_i4_r8_d1_tst.lincoa
    #
    # See also
    # https://forums.developer.nvidia.com/t/bug-of-nvfortran-25-7-with-empty-arrays
    # https://github.com/zequipe/test_compiler/blob/master/test_bd.f90
    #
    # The following line removes the code concerned. Re-test the code when nvfortran is updated.
    STR="Anew"
    sed -i "/$STR/d" "$POWALG"
fi

exit 0
