#!/usr/bin/env bash
# This script pre-processes the Fortran source code for nvfortran.

DIR="$(realpath "$1")"
POWALG="$DIR/common/powalg.f90"

if ! basename "$DIR" | grep -q ".test\|test." || ! [[ -d "$DIR" ]] ; then
    printf "\n%s is not a testing directory.\n\nExit.\n\n" "$DIR"
    exit 1
fi

# Do nothing as of nvfortran 26.1, although bugs still exist:
# https://forums.developer.nvidia.com/t/a-bug-of-nvfortran-26-1regarding-empry-arrays/358946
# https://github.com/zequipe/test_compiler/blob/master/test_empty_array.f90

exit 0
